### PR TITLE
Able to fetch and predict 

### PR DESCRIPTION
**Pull request by samuelmaina**
Able to fetch and predict with eml dataset.
The problem was with the service.py. The previous service was using 
```
class Model(object):
   def __init__(self):
          self.DATA_FILE = "_data.csv"
          self.PRED_FILE = "_pred.csv"
          self.RUN_FILE = "_run.sh"
          self.LOG_FILE = "_run.log"
```
but the new service.py
```
class Model(object):
    def __init__(self):
        self.DATA_FILE = "_data.csv"
        self.OUTPUT_FILE = "_output.csv"
        self.RUN_FILE = "_run.sh"
        self.LOG_FILE = "run.log"
```
I haven't studied into the inner issue why this is causing but different naming of the temp output file can have  an issue with output parsing

### CODE REVIEW

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

WE usually do not modify these files so it would be good to understand why this changes affect the output of the model! Let's dig into it before merging the code.
I'm tagging @miquelduranfrigola so he can also follow

**Comment by samuelmaina** [comment]
Thanks @GemmaTuron ,
We will discuss this issue with him in our 1:1  today.

**Comment by GemmaTuron** [comment]
Ok,
@samuelmaina Before the meeting please dig into the issue and provide an update on the issue so that we can better help you.

**Comment by miquelduranfrigola** [comment]
Thanks @samuelmaina and @GemmaTuron 

This is interesting. Yes @samuelmaina - let's have a look in our 1:1 meeting tomorrow.

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron we have discussed this with @samuelmaina - all changes are perfectly understood and we are ready to merge the PR!

**Pull request merged**
